language: cpp
sudo: false
dist: bionic
addons:
  apt:
    packages:
    - libboost-regex-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-test-dev
    - libssl-dev
compiler:
  - gcc
before_script:
  - cmake . -DTests=ON -DCMAKE_BUILD_TYPE=Debug
  - pip install --user cpp-coveralls
script:
  - make
  - bin/manalyze --version
  - bin/manalyze --help
  - bin/manalyze-tests
  - bin/hash-library-test
after_success:
  - git clone https://github.com/radare/radare2-regressions.git
  # Run Manalyze on r2's problematic binaries
  - travis_wait 30 bin/manalyze -r radare2-regressions/bins/pe/ >/dev/null 2>&1
  - bin/manalyze -r radare2-regressions/bins/fuzzed/ -ojson >/dev/null 2>&1
  - bin/manalyze -d all -p all --hashes --extract /tmp/ test/testfiles/manatest.exe test/testfiles/manatest2.exe >/dev/null
  - bin/manalyze -d all -p all --hashes -o json test/testfiles/manatest3.exe >/dev/null
  # The VT plugin is excluded as testing it properly would require commiting API keys.
  - coveralls --exclude external/yara --exclude test --exclude plugins/plugin_virustotal/ --exclude examples --exclude radare2-regressions --gcov gcov-4.8 >/dev/null
